name: Deploy Imagine n Chat to Systest
concurrency: main_environment
on:
  push:
    branches: ['main']
env:
  FOLDER: /home/systest/groupchat
jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code    
        uses: actions/checkout@master
        
      - name: Package 
        uses: actions/upload-artifact@v3
        with:
          name: GroupChatArtifacts
          path: |
            *
  Deploy:
    runs-on: ubuntu-latest
    needs: Package 
    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: GroupChatArtifacts
          path: .
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.SERVERUSERNAME  }}
          password: ${{ secrets.SERVERPASSWORD  }}
          source: ./**
          target: ${{ env.FOLDER }}
